"""Business search taxonomy and category classification.

BUSINESS_CATEGORIES casts a wide net of keyword searches. SEARCH_KEYWORDS is the
flattened list used to drive queries; category_for_types maps a place's Google
types back to one of the category groups.
"""

from __future__ import annotations

BUSINESS_CATEGORIES: dict[str, list[str]] = {
    "food_beverage": [
        "restaurant",
        "cafe",
        "coffee shop",
        "bakery",
        "bar",
        "pub",
        "ice cream shop",
        "frozen yogurt",
        "juice bar",
        "smoothie shop",
        "food truck",
        "catering",
        "deli",
        "pizza place",
        "brewery",
        "winery",
        "dessert shop",
        "bubble tea",
        "donut shop",
        "bagel shop",
        "sandwich shop",
        "burger joint",
        "taco shop",
        "sushi",
        "buffet",
        "steakhouse",
        "seafood restaurant",
        "breakfast spot",
        "brunch",
        "fast food",
        "food delivery",
        "meal prep",
        "ghost kitchen",
    ],
    "retail": [
        "clothing store",
        "boutique",
        "fashion boutique",
        "jewelry store",
        "gift shop",
        "bookstore",
        "antique store",
        "furniture store",
        "home decor",
        "flower shop",
        "pet store",
        "toy store",
        "sporting goods",
        "electronics store",
        "shoe store",
        "thrift store",
        "vintage shop",
        "consignment shop",
        "specialty store",
        "hobby shop",
        "art supply store",
        "music store",
        "bike shop",
        "outdoor gear",
        "department store",
        "convenience store",
        "liquor store",
        "smoke shop",
        "cbd store",
        "nutrition store",
        "vitamin shop",
        "beauty supply",
    ],
    "health_wellness": [
        "fitness center",
        "gym",
        "yoga studio",
        "pilates studio",
        "spa",
        "massage",
        "nail salon",
        "hair salon",
        "barber shop",
        "beauty salon",
        "med spa",
        "chiropractor",
        "physical therapy",
        "acupuncture",
        "wellness center",
        "martial arts",
        "dance studio",
        "crossfit",
        "boxing gym",
        "climbing gym",
        "meditation center",
        "tanning salon",
        "eyebrow threading",
        "lash extensions",
        "waxing",
        "tattoo parlor",
        "piercing shop",
        "float spa",
        "cryotherapy",
    ],
    "professional_services": [
        "dentist",
        "orthodontist",
        "optometrist",
        "veterinarian",
        "law firm",
        "accounting firm",
        "insurance agency",
        "real estate agency",
        "financial advisor",
        "tax preparation",
        "tutoring center",
        "consulting firm",
        "marketing agency",
        "travel agency",
        "employment agency",
        "property management",
        "title company",
        "mortgage broker",
        "investment firm",
        "architect",
        "engineer",
        "psychologist",
        "counselor",
        "psychiatrist",
        "pediatrician",
    ],
    "home_services": [
        "plumber",
        "electrician",
        "hvac",
        "landscaping",
        "roofing",
        "painting contractor",
        "home cleaning",
        "pest control",
        "handyman",
        "flooring",
        "window installation",
        "garage door",
        "carpet cleaning",
        "pressure washing",
        "pool service",
        "fence contractor",
        "concrete contractor",
        "tree service",
        "gutter cleaning",
        "locksmith",
        "appliance repair",
        "furniture repair",
        "home inspection",
        "renovation",
        "kitchen remodeling",
        "bathroom remodeling",
        "deck builder",
    ],
    "automotive": [
        "auto repair",
        "car dealership",
        "auto detailing",
        "tire shop",
        "oil change",
        "car wash",
        "auto parts",
        "motorcycle dealer",
        "transmission repair",
        "brake repair",
        "muffler shop",
        "auto glass",
        "body shop",
        "paint shop",
        "car rental",
        "towing service",
        "diesel repair",
        "rv dealer",
        "boat dealer",
        "auto upholstery",
    ],
    "entertainment_recreation": [
        "bowling alley",
        "arcade",
        "escape room",
        "mini golf",
        "movie theater",
        "music venue",
        "comedy club",
        "art gallery",
        "museum",
        "dance studio",
        "music lessons",
        "art studio",
        "karaoke",
        "billiards",
        "go kart",
        "laser tag",
        "trampoline park",
        "skating rink",
        "rock climbing",
        "paintball",
        "axe throwing",
        "golf course",
        "country club",
        "tennis club",
        "sports complex",
    ],
    "education_childcare": [
        "daycare",
        "preschool",
        "private school",
        "tutoring center",
        "music school",
        "art school",
        "driving school",
        "language school",
        "after school program",
        "summer camp",
        "childcare center",
        "montessori school",
        "test prep",
        "college prep",
        "trade school",
    ],
    "events_hospitality": [
        "event venue",
        "wedding venue",
        "party rental",
        "event planning",
        "photographer",
        "videographer",
        "dj service",
        "catering",
        "hotel",
        "motel",
        "bed and breakfast",
        "airbnb",
        "vacation rental",
        "banquet hall",
        "conference center",
        "coworking space",
    ],
    "manufacturing_wholesale": [
        "manufacturer",
        "wholesaler",
        "distributor",
        "warehouse",
        "industrial supply",
        "equipment rental",
        "machine shop",
        "metal fabrication",
        "woodworking",
        "printing service",
        "embroidery",
        "screen printing",
        "sign shop",
        "packaging",
    ],
    "agriculture_pets": [
        "farm",
        "ranch",
        "nursery",
        "garden center",
        "pet grooming",
        "dog training",
        "pet boarding",
        "pet daycare",
        "animal shelter",
        "horse stable",
        "feed store",
        "agricultural supply",
    ],
    "transportation_logistics": [
        "trucking company",
        "logistics",
        "freight",
        "moving company",
        "storage facility",
        "shipping",
        "courier service",
        "taxi service",
        "limo service",
        "bus company",
        "delivery service",
    ],
}

# Flattened keyword list used to drive searches.
SEARCH_KEYWORDS: list[str] = [kw for kws in BUSINESS_CATEGORIES.values() for kw in kws]


def keywords_for(categories: list[str] | None = None) -> list[str]:
    """Return the search keywords for the given category keys (all if None)."""
    if not categories:
        return list(SEARCH_KEYWORDS)
    out: list[str] = []
    for key in categories:
        out.extend(BUSINESS_CATEGORIES.get(key, []))
    return out


def category_for_types(types_list: list[str]) -> str:
    """Best-effort category for a place, from its Google Place types."""
    for category, keywords in BUSINESS_CATEGORIES.items():
        for keyword in keywords:
            parts = keyword.lower().replace("_", " ").split()
            for place_type in types_list:
                clean = place_type.lower().replace("_", " ")
                if all(part in clean for part in parts):
                    return category
    return "other"
